### ISSUE TITLE
I got higher results

### ISSUE THREAD

**Issue by ShiyuNee** [algoprog/Faspect#5]
Why i got higher results using your uploaded checkpoint and code.
Here are my results:
![image](https://user-images.githubusercontent.com/74317813/234792176-33cef55f-29b3-49ac-998d-a5342c977a75.png)

**Comment by ShiyuNee** [comment]
> Hi @ShiyuNee , can you give some details on (a) how you initialize the model and (b) how your evaluation code looks like? Do you crop number of facets generated to the number of groundtruth facets? How did you get around the assertion [here](https://github.com/algoprog/Faspect/blob/main/evaluation.py#L8)?

I think we should append "" to candidate facets or ground-truth facets to get the same length.

**Comment by algoprog** [comment]
Hi, I just updated the evaluation code, indeed you need to make sure both sets have 5 elements by appending empty strings if required. I apologize for the late reply.
